POST http://127.0.0.1:8000/api/orders/create/order-item/
Accept: application/json
Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjA4NTYyMjAxLCJqdGkiOiJiMTg5OWUzZGZjNzI0NzY3OWE4NGMwNzZlZWYxMjQ2MiIsInVzZXJfaWQiOjE4fQ.bN_ITDyNK4nqzzUNc3Y0l_4aGCi3c86u40ZV3CUSFlE


{
"item": "3" ,
"quantity" : "1000"
}
