# Generated by Django 3.1.3 on 2020-11-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201116_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
