# Generated by Django 3.1.3 on 2020-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201116_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='Phone Number'),
        ),
    ]
