# Generated by Django 3.1.3 on 2020-11-16 18:01

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201116_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=11, unique=True, validators=[users.models.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
