# Generated by Django 3.1.3 on 2020-11-29 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_remove_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, related_name='orderer', to='users.customuser'),
            preserve_default=False,
        ),
    ]
