# Generated by Django 3.1.3 on 2020-11-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201114_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='modified_date',
        ),
    ]
